apiVersion: v1
kind: Service
metadata:
  name: mytestapp-mongodb-agent-service
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mytestapp-mongodb-agent
spec:
  serviceName: mytestapp-mongodb-agent-service
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        appname: mytestapp
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: appname
                  operator: In
                  values:
                  - mytestapp
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mytestapp-mongodb-agent-container
          image: XXXX/automation-agent
          args:
            - "/opt/mongodb-mms-automation/bin/mongodb-mms-automation-agent"
            - "--mmsGroupId=YYYY"
            - "--mmsApiKey=ZZZZ"
            - "--mmsBaseUrl=https://cloud.mongodb.com"
            - "--mmsConfigBackup=/var/lib/mongodb-mms-automation/mongodb-mms-automation-cluster-backup.json"
            - "--logLevel=INFO"
          resources:
            requests:
              cpu: 0.5
              memory: 2Gi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mytestapp-data-storage-claim
              mountPath: /data
            - name: mytestapp-downloads-storage-claim
              mountPath: /var/lib/mongodb-mms-automation
  volumeClaimTemplates:
  - metadata:
      name: mytestapp-data-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: mytestapp-downloads-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
